import fs from "node:fs";
import path from "node:path";
import {execFileSync} from "node:child_process";
import {fileURLToPath} from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const upstreamRoot = path.join(projectRoot, "vendor", "5etools-src");
const required = [
  "classes.html",
  "actions.html",
	"conditionsdiseases.html",
	"variantrules.html",
	"quickreference.html",
	"spells.html",
	"races.html",
	"backgrounds.html",
	"feats.html",
	"optionalfeatures.html",
	"cultsboons.html",
	"charcreationoptions.html",
	"rewards.html",
	"languages.html",
	"deities.html",
	"vehicles.html",
	"recipes.html",
	"homecrafts.html",
	"data/zh-TW/class.json",
	"data/zh-TW/class/index.json",
	"data/zh-TW/site.json",
	"data/zh-TW/rules/index.json",
	"data/zh-TW/rules/actions.json",
	"data/zh-TW/rules/generated/bookref-quick.json",
	"data/zh-TW/spells/index.json",
	"data/zh-TW/spells/spells-phb.json",
	"data/zh-TW/spells/spells-xphb.json",
	"data/zh-TW/spells/fluff-spells-xphb.json",
	"data/zh-TW/character-options/index.json",
	"data/zh-TW/character-options/races.json",
	"data/zh-TW/character-options/backgrounds.json",
	"data/zh-TW/character-options/feats.json",
	"data/zh-TW/character-options/optionalfeatures.json",
	"data/zh-TW/items/index.json",
	"data/zh-TW/items/items-000.json",
	"data/zh-TW/items/items-008.json",
	"data/zh-TW/items/item-groups.json",
	"data/zh-TW/items/items-base.json",
	"data/zh-TW/items/magicvariants.json",
	"data/zh-TW/items/fluff-items.json",
	"data/zh-TW/bestiary/index.json",
	"data/zh-TW/bestiary/bestiary-mm.json",
	"data/zh-TW/bestiary/bestiary-xmm.json",
	"data/zh-TW/bestiary/fluff-bestiary-mm.json",
	"data/zh-TW/bestiary/legendarygroups.json",
	"data/zh-TW/cults-boons/index.json",
	"data/zh-TW/cults-boons/cultsboons.json",
	"data/zh-TW/reference-pages/index.json",
	"data/zh-TW/reference-pages/charcreationoptions.json",
	"data/zh-TW/reference-pages/fluff-charcreationoptions.json",
	"data/zh-TW/reference-pages/rewards.json",
	"data/zh-TW/reference-pages/fluff-rewards.json",
	"data/zh-TW/reference-pages/languages.json",
	"data/zh-TW/reference-pages/fluff-languages.json",
	"data/zh-TW/reference-pages/deities.json",
	"data/zh-TW/adventures/adventure-cos.json",
	"data/zh-TW/adventures/adventure-hotdq.json",
	"data/zh-TW/adventures/adventure-rot.json",
	"js/zh-tw/adventure-i18n.js",
	"data/zh-TW/craft-pages/index.json",
	"data/zh-TW/craft-pages/vehicles.json",
	"data/zh-TW/craft-pages/fluff-vehicles.json",
	"data/zh-TW/craft-pages/recipes.json",
	"data/zh-TW/craft-pages/fluff-recipes.json",
	"data/zh-TW/craft-pages/homecrafts.json",
	"data/zh-TW/craft-pages/fluff-homecrafts.json",
	"js/zh-tw/class-i18n.js",
	"js/zh-tw/class-body-i18n.js",
	"js/zh-tw/site-i18n.js",
	"js/zh-tw/rules-i18n.js",
	"js/zh-tw/quick-reference-i18n.js",
	"js/zh-tw/content-i18n.js",
	"node/zh-tw/test-class-i18n.mjs",
	"node/zh-tw/test-class-body-i18n-full.mjs",
	"node/zh-tw/test-class-page-runtime.mjs",
	"node/zh-tw/test-site-i18n.mjs",
	"node/zh-tw/test-rules-i18n.mjs",
	"node/zh-tw/test-quick-reference-i18n.mjs",
	"node/zh-tw/test-content-i18n.mjs",
	"node/zh-tw/validate-full-class-translations.mjs",
	"node/zh-tw/validate-core-rules.mjs",
	"node/zh-tw/validate-content-translations.mjs",
	"node/zh-tw/validate-character-options-translations.mjs",
	"node/zh-tw/test-item-i18n.mjs",
	"node/zh-tw/test-item-page-runtime.mjs",
	"node/zh-tw/validate-item-translations.mjs",
	"node/zh-tw/test-monster-i18n.mjs",
	"node/zh-tw/test-monster-page-runtime.mjs",
	"node/zh-tw/validate-monster-translations.mjs",
	"node/zh-tw/test-small-fragments-and-bastions.mjs",
	"node/zh-tw/test-cults-boons-i18n.mjs",
	"node/zh-tw/test-reference-pages-i18n.mjs",
	"node/zh-tw/test-craft-pages-i18n.mjs",
];

for (const relativePath of required) {
  if (!fs.existsSync(path.join(upstreamRoot, relativePath))) throw new Error(`Missing applied file: ${relativePath}`);
}

const runNode = (script, ...args) => execFileSync(process.execPath, [script, ...args], {cwd: upstreamRoot, stdio: "inherit"});
for (const script of [
  "js/classes.js",
  "js/render-class.js",
  "js/actions.js",
  "js/conditionsdiseases.js",
  "js/variantrules.js",
  "js/quickreference.js",
  "js/bookutils.js",
	"js/listpage.js",
	"js/multisource.js",
  "js/render.js",
  "js/render-actions.js",
  "js/render-conditionsdiseases.js",
	"js/render-variantrules.js",
	"js/filter-spells.js",
	"js/render-spells.js",
	"js/spells.js",
	"js/backgrounds.js",
	"js/feats.js",
	"js/filter-backgrounds.js",
	"js/filter-common.js",
	"js/filter-feats.js",
	"js/filter-optionalfeatures.js",
	"js/filter-races.js",
	"js/filter-items.js",
	"js/filter/filter/filter-filter-ability-score.js",
	"js/optionalfeatures.js",
	"js/races.js",
	"js/render-races.js",
	"js/bastions.js",
	"js/items.js",
	"js/bestiary.js",
	"js/render-bestiary.js",
	"js/render-dice.js",
	"js/render-items.js",
	"js/cultsboons.js",
	"js/filter-cultsboons.js",
	"js/render-cultsboons.js",
	"js/charcreationoptions.js",
	"js/filter-charcreationoptions.js",
	"js/render-charcreationoptions.js",
	"js/rewards.js",
	"js/filter-rewards.js",
	"js/render-rewards.js",
	"js/languages.js",
	"js/filter-languages.js",
	"js/render-languages.js",
	"js/deities.js",
	"js/filter-deities.js",
	"js/render-deities.js",
	"js/vehicles.js",
	"js/filter-vehicles.js",
	"js/recipes.js",
	"js/filter-recipes.js",
	"js/render-recipes.js",
	"js/homecrafts.js",
	"js/filter-homecrafts.js",
	"js/render-homecrafts.js",
	"js/utils.js",
	"js/utils-list.js",
	"js/utils-dataloader/utils-dataloader-dataloader.js",
  "js/zh-tw/class-i18n.js",
  "js/zh-tw/class-body-i18n.js",
	"js/zh-tw/site-i18n.js",
	"js/zh-tw/rules-i18n.js",
	"js/zh-tw/quick-reference-i18n.js",
	"js/zh-tw/content-i18n.js",
]) execFileSync(process.execPath, ["--check", script], {cwd: upstreamRoot, stdio: "inherit"});

runNode("node/zh-tw/validate-glossary.mjs");
runNode("node/zh-tw/test-class-i18n.mjs");
runNode("node/zh-tw/test-class-body-i18n.mjs");
runNode("node/zh-tw/test-class-body-i18n-full.mjs");
runNode("node/zh-tw/test-class-page-runtime.mjs");
runNode("node/zh-tw/validate-full-class-translations.mjs");
runNode("node/zh-tw/apply-site-i18n-html.mjs", "--check");
runNode("node/zh-tw/test-site-i18n.mjs");
runNode("node/zh-tw/validate-core-rules.mjs");
runNode("node/zh-tw/test-rules-i18n.mjs");
runNode("node/zh-tw/test-quick-reference-i18n.mjs");
runNode("node/zh-tw/validate-content-translations.mjs");
runNode("node/zh-tw/validate-character-options-translations.mjs");
runNode("node/zh-tw/test-content-i18n.mjs");
runNode("node/zh-tw/validate-item-translations.mjs");
runNode("node/zh-tw/test-item-i18n.mjs");
runNode("node/zh-tw/test-item-page-runtime.mjs");
runNode("node/zh-tw/validate-monster-translations.mjs");
runNode("node/zh-tw/test-monster-i18n.mjs");
runNode("node/zh-tw/test-monster-page-runtime.mjs");
runNode("node/zh-tw/test-small-fragments-and-bastions.mjs");
runNode("node/zh-tw/test-cults-boons-i18n.mjs");
runNode("node/zh-tw/test-reference-pages-i18n.mjs");
runNode("node/zh-tw/test-adventure-cos-i18n.mjs");
runNode("node/zh-tw/test-adventure-tyranny-i18n.mjs");
runNode("node/zh-tw/test-craft-pages-i18n.mjs");
execFileSync("git", ["diff", "--check"], {cwd: upstreamRoot, stdio: "inherit"});
console.log("zh-TW interface, Class, core-rules, Quick Reference, spells, character-options, items, monsters, Bastions, cults/boons, reference pages, CoS/Tyranny of Dragons adventures, vehicles, recipes, and homecrafts overlay verification passed.");
